# Generated by Django 4.0.4 on 2022-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_board_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
